/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOperatorAllowlist,
  IOperatorAllowlistInterface,
} from "../../../../../@imtbl/contracts/contracts/allowlist/IOperatorAllowlist";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
    ],
    name: "isAllowlisted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IOperatorAllowlist__factory {
  static readonly abi = _abi;
  static createInterface(): IOperatorAllowlistInterface {
    return new Interface(_abi) as IOperatorAllowlistInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IOperatorAllowlist {
    return new Contract(address, _abi, runner) as unknown as IOperatorAllowlist;
  }
}
