/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ImmutableERC721 } from "./ImmutableERC721";
export type { ImmutableERC721MintByID } from "./ImmutableERC721MintByID";
