/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IOperatorAllowlist } from "./IOperatorAllowlist";
export type { OperatorAllowlistEnforced } from "./OperatorAllowlistEnforced";
